def get_labels_dict():
    labels = {
                'person':'사람',
                'bicycle':'자전거',
                'car':'자동차',
                'motorcycle':'오토바이',
                'airplane':'비행기',
                'bus':'버스',
                'train':'기차',
                'truck':'트럭',
                'boat':'보트',
                'traffic light':'신호등',
                'fire hydrant':'소화전',
                'stop sign':'정지신호',
                'parking meter':'주차권',
                'bench':'벤치',
                'bird':'새',
                'cat':'고양이',
                'dog':'강아지',
                'horse':'말',
                'sheep':'양',
                'cow':'소',
                'elephant':'코끼리',
                'bear':'곰',
                'zebra':'얼룩말',
                'giraffe':'기린',
                'backpack':'가방',
                'umbrella':'우산',
                'handbag':'손가방',
                'tie':'넥타이',
                'suitcase':'여행가방',
                'frisbee':'프리스비',
                'skis':'스키',
                'snowboard':'스노우보드',
                'sports ball':'공',
                'kite':'연',
                'baseball bat':'방망이',
                'baseball glove':'글러브',
                'skateboard':'스케이트보드',
                'surfboard':'서핑보드',
                'tennis racket':'라켓',
                'bottle':'병',
                'wine glass':'와인잔',
                'cup':'컵',
                'fork':'포크',
                'knife':'칼',
                'spoon':'숟가락',
                'bowl':'그릇',
                'banana':'바나나',
                'apple':'사과',
                'sandwich':'샌드위치',
                'orange':'오랜지',
                'broccoli':'브로콜리',
                'carrot':'당근',
                'hot dog':'핫도그',
                'pizza':'피자',
                'donut':'도넛',
                'cake':'케이크',
                'chair':'의자',
                'couch':'소파',
                'potted plant':'화분',
                'bed':'침대',
                'dining table':'식탁',
                'toilet':'화장실',
                'tv':'티비',
                'laptop':'노트북',
                'mouse':'마우스',
                'remote':'리모컨',
                'keyboard':'키보드',
                'cell phone':'전화기',
                'microwave':'전자레인지',
                'oven':'오븐',
                'toaster':'토스트기',
                'sink':'싱크대',
                'refrigerator':'냉장고',
                'book':'책',
                'clock':'시계',
                'vase':'꽃병',
                'scissors':'가위',
                'teddy bear':'곰인형',
                'hair drier':'드라이기',
                'toothbrush':'칫솔',
                }
    
    return labels

def convertK2V():
    labels = get_labels_dict()
    converted_labels = {}
    for i,v in labels.items():
        converted_labels[v] = i
    
    return converted_labels